### ISSUE TITLE
Typo on Pg. 55's Map Example

### ISSUE THREAD

**Issue by lozandier** [l3x/learn-fp-go#6]
The map example on Page 55 has typos that makes the code unable to be ran with the expected results
- `planets` used instead of `names` within `collection.NewFromSlice()`
- `strings.Join` should be `strings.Join([]string{"Hey", v.(string)}, " ")` or `strings.Join([]string{"Hey ", v.(string)}, "")`

With these typos fixed

```go
names := []interface{}{
  "Alice",
  "Bob",
  "Cindy",
}

collection := collections.NewFromSlice(names)
collection = collection.Map(func(v interface{}) interface{} {
  return strings.Join([]string{"Hey", v.(string)}, " ")
})
println(collection) // or the use of fmt.Println(collection)
```

**Comment by l3x** [comment]
Great catch! 

I initially did not get a chance to proof the chapters before the book was published. The discrepancies are mainly at the beginning of the book. The publisher should send you the revised copy (no charge) when it's ready.

I added your catch to https://lexsheehan.blogspot.com/2017/11/corrections-for-learning-fp-in-go-book.html

Thanks!
