### ISSUE TITLE
Memoization code is not properly caching results

### ISSUE THREAD

**Issue by ghost** [l3x/learn-fp-go#7]
The book describes a recursive `fib` function to calculate a number in the fibonacci sequence as well as a `Memoize` function to cache results from function calls with the same arguments. The Memoize function is never called in the code presented by the book and the `fibMem` variable is defined but never initialised. 

In this repository, there are two files for memoize.go and memoize.go_ORIG. memoize.go differs slightly from what's in the book because it initialises `fibMem` as `Memoize(fib)`. While this produces the correct output, it doesn't, in fact, actually cache any results because the recursion is still calling the "unmemoized" version of the original `fib` function. 

memoize.go_ORIG works correctly but isn't the code that appears in the book. Which version was used to generate the benchmarks?

**Comment by craftgear** [comment]
I encountered the same problem :(

**Comment by l3x** [comment]
Hey guys, especially @benjaminjosephw - So sorry I'm just now noticing your message.  

Did you know that the publisher has a revised version of the book available? It should be free.
(The original version was mostly a draft version that was hastily published, but has since been corrected.)

I'll look into to this.  And get you an answer within 24 hours.

In the meantime, you might enjoy this presentation I gave for the Atlanta Functional Programming Meetup Group: https://www.youtube.com/watch?v=HRrP_P0PwFU

p.s. This is definitely the right place to create issues with the code/book, but  feel free to link to me at https://www.linkedin.com/in/lexsheehan/  I'm likely respond more quickly there.

Thanks!
Lex

**Comment by l3x** [comment]
Sorry for the confusion.  

In hindsight, I could have done a better job with the wording in this section.

There are two code examples in this section.

The first runs main.go:
```
func main() {
    println(fibonacci.FibSimple(4))
    println(fibonacci.FibMemoized(5))
    println(fibonacci.FibChanneled(6))
}
```
and produces this output:
```
3
5
8
```

The second, and main purpose of the code in **learn-fp-go/1-functional-fundamentals/ch01-pure-fp/02_fib** is to illustrate how we can test and benchmark the Fibonacci Sequence using all three FP techniques (Simple, Memoized, Channel).

We run the second example like this: `go test -bench=. ./...`

When `go test -bench=. ./...` is executed, **fibMem** variable is defined, initialized and executed in:

```
func FibMemoized(n int) int {
	return fibMem(n)
}
```

The memoize.go_ORIG file should not exist as it is not used to run the benchmark test.

Does that explanation clear this up for you?

**Comment by l3x** [comment]
FYI - This is what my console looks like when running that code:

```
 ~/dev/02_fib $ go-run
3
5
8
  ~/dev/02_fib $ go test -bench=. ./...
?   	_/Users/lex/dev/02_fib	[no test files]
goos: darwin
goarch: amd64
pkg: fibonacci
BenchmarkFibChanneled-8     	  500000	      3638 ns/op
BenchmarkFibChanneled0-8    	 2000000	       911 ns/op
BenchmarkFibChanneled1-8    	 1000000	      1559 ns/op
BenchmarkFibChanneled2-8    	 1000000	      1646 ns/op
BenchmarkFibChanneled3-8    	 1000000	      2264 ns/op
BenchmarkFibChanneled4-8    	 1000000	      2278 ns/op
BenchmarkFibChanneled5-8    	  500000	      2967 ns/op
BenchmarkFibChanneled6-8    	  500000	      2963 ns/op
BenchmarkFibChanneled10-8   	  300000	      4330 ns/op
BenchmarkFibChanneled21-8   	  200000	      8399 ns/op
BenchmarkFibChanneled43-8   	  100000	     15692 ns/op
BenchmarkFibMemoized-8      	100000000	        22.9 ns/op
BenchmarkFibMemoized0-8     	100000000	        17.4 ns/op
BenchmarkFibMemoized1-8     	100000000	        17.3 ns/op
BenchmarkFibMemoized2-8     	100000000	        18.6 ns/op
BenchmarkFibMemoized3-8     	100000000	        19.8 ns/op
BenchmarkFibMemoized4-8     	100000000	        20.1 ns/op
BenchmarkFibMemoized5-8     	100000000	        21.0 ns/op
BenchmarkFibMemoized6-8     	100000000	        18.5 ns/op
BenchmarkFibMemoized10-8    	100000000	        22.3 ns/op
BenchmarkFibMemoized21-8    	100000000	        19.2 ns/op
BenchmarkFibMemoized43-8    	100000000	        20.3 ns/op
BenchmarkFibSimple-8        	20000000	       101 ns/op
BenchmarkFibSimple0-8       	500000000	         3.30 ns/op
BenchmarkFibSimple1-8       	1000000000	         2.95 ns/op
BenchmarkFibSimple2-8       	1000000000	         3.00 ns/op
BenchmarkFibSimple3-8       	200000000	         7.80 ns/op
BenchmarkFibSimple4-8       	100000000	        13.2 ns/op
BenchmarkFibSimple5-8       	50000000	        22.9 ns/op
BenchmarkFibSimple6-8       	50000000	        37.5 ns/op
BenchmarkFibSimple21-8      	   30000	     56121 ns/op
BenchmarkFibSimple43-8      	       1	2180868185 ns/op
PASS
ok  	fibonacci	68.586s
?   	mypackage	[no test files]
  ~/dev/02_fib $ goenv info
STATUS: √
GOROOT: /usr/local/Cellar/go/1.11/libexec
GOPATH: /Users/lex/GOPATHs/learn-fp-go/src/github.com/l3x/learn-fp-go/1-functional-fundamentals/ch01-pure-fp/02_fib/vendors:/Users/lex/GOPATHs/learn-fp-go/src/github.com/l3x/learn-fp-go/1-functional-fundamentals/ch01-pure-fp/02_fib
GOBIN : /Users/lex/GOPATHs/learn-fp-go/src/github.com/l3x/learn-fp-go/1-functional-fundamentals/ch01-pure-fp/02_fib/bin
GOOS  : darwin
GOARCH: amd64
```

**Comment by l3x** [comment]
FYI - I like using delve for debugging, which has issues with Go 1.11, so I had to back-version Go like this:
```
pushd "$(brew --repo homebrew/core)"
git log Formula/go.rb
git checkout -b go-1.9.4 a478f001d1664d5e954339a51245ce2ad672f4fd
brew unlink go
HOMEBREW_NO_AUTO_UPDATE=1 brew install go
brew list go --versions
```

We can then cleanup by reverting the downgrade of our homebrew installation like so:
```
git checkout master
git branch -d go-1.9.4
popd
```

**Comment by l3x** [comment]
Please let me know if you'd like any more clarification.  

I'll include it in an article, "Using Go Tooling to Benchmark FP in Go", that I'm planning to write for https://www.smoothterminal.com/

**Comment by craftgear** [comment]
Hi, @l3x thanks for your help.

Still, what I'm confused about is not benchmarking.
It is that a file named "memoize.go" doesn't do memoize.

https://github.com/l3x/learn-fp-go/blob/master/1-functional-fundamentals/ch01-pure-fp/02_fib/src/fibonacci/meomoize.go#L28
Inside `fib` function, it calls itself recursively and thus there is no memoization happened.

I think the following code would memoize computed results:
```
return fibMem(x-2) + fibMemb(x-1)
```

**Comment by jeffkayser2** [comment]
`package main

import (
        "fmt"
)

type funcIntInt func(int) int

func main () {
        var fibMem funcIntInt
        fibMem = memoizeFuncIntInt(func(x int) int {
                if x == 0 {
                        return 0
                } else if x <= 2 {
                        return 1
                } else {
                        return fibMem(x-2) + fibMem(x-1)
                }
        })
        fmt.Printf("%v\n", fibMem(51))
}

func memoizeFuncIntInt(f funcIntInt) funcIntInt {
        cache := make(map[int]int)
        return func(key int) int {
                if val, found := cache[key]; found {
                        return val
                }
                temp := f(key)
                cache[key] = temp
                return temp
        }
}
`

**Comment by l3x** [comment]
@craftgear Do you have a copy of the book's revision?  On page 21, it describes memoization as follows:

> Memoization is an optimization technique used to increase performance by storing the results of expensive function calls and returning the cached result when the same input occurs again.

The Memoize function (below) is defined in the **memoize.go** file:

```
func Memoize(mf Memoized) Memoized {
	cache := make(map[int]int)
	return func(key int) int {
		if val, found := cache[key]; found {
			return val
		}
		temp := mf(key)
		cache[key] = temp
		return temp
	}
}
```

When the following line in the **memoize_test.go** file is executed:

```
if v := FibMemoized(ft.a); v != ft.expected {
```

The FibMemoized function is called:

```
func FibMemoized(n int) int {
	return fibMem(n)
}
```

The following line is subsequently (nearly immediately) executed:

```
if val, found := cache[key]; found {
			return val
		}
```

<= That is where the cache is queried (and hence the memoization occurs).

If the value is not found, then `fib` is called via `mf(key)`:

```
temp := mf(key)
```

Recursion occurs in that fib function, either returning a leaf value (of 0 or 1) or recursing until a leaf is found.

If you step through the code in a debugger or make extensive use of `fmt.Println`'s you'll see what I'm talking about.

The graph in the book showing the fibonacci tree of values will help a lot.

**Comment by craftgear** [comment]
Hi l3x, thanks for your explanation.

I think I understand what you explained, except the page number.
As I read a digital version of your book ;-)

Anyway, now the only thing I really don't get is, then why `FibMemoized` is as slow as  `FibSimple` ?

When I run this:
```
func main() {
^   println(fibonacci.FibSimple(45))
^   // println(fibonacci.FibMemoized(45))
^   // println(fibonacci.FibChanneled(6))
}
```
It took 5.22 secs on my machine. ( I use `time` command )

Then this:
```
func main() {
^   // println(fibonacci.FibSimple(45))
^   println(fibonacci.FibMemoized(45))
^   // println(fibonacci.FibChanneled(6))
}
```
 took 5.28 secs.

Do you have any clues?

Thanks in advance.



BTW, when I run this one: https://github.com/craftgear/fp_in_go/blob/master/fibonacci/memoized_fib.go

It took only 0.28 secs
